PLATFORM_FLAVOR ?= mercury

include core/arch/arm/cpu/cortex-armv8-0.mk

ifeq ($(PLATFORM_FLAVOR),mercury)
$(call force,CFG_TEE_CORE_NB_CORE,4)
endif

$(call force,CFG_CA_UART,y)
$(call force,CFG_SECURE_TIME_SOURCE_CNTPCT,y)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)

CFG_NUM_THREADS ?= 8
CFG_CRYPTO_WITH_CE ?= y

ifeq ($(PLATFORM_FLAVOR),mercury)
CFG_CORE_HEAP_SIZE ?= 73728
CFG_CACHE_API ?= y
CFG_SECURE_DATA_PATH ?= n
CFG_TEE_SDP_MEM_BASE ?= 0x3E800000
CFG_TEE_SDP_MEM_SIZE ?= 0x00400000
endif

ifeq ($(PLATFORM_FLAVOR),mercury)
CFG_CONSOLE_UART ?= 2
CFG_DRAM_SIZE_GB ?= 2
endif

CFG_TZDRAM_START ?= 0x3F000000
CFG_TZDRAM_SIZE ?= 0x01000000
CFG_SHMEM_START ?= 0x3EE00000
CFG_SHMEM_SIZE ?= 0x00200000
CFG_TEE_RAM_VA_SIZE ?= 0x00200000
CFG_DRAM1_BASE ?= 0x40000000

CFG_EMBED_DTB_SOURCE_FILE ?= mercury.dts
